<div id="map" style="width: 100%; height: 500px"></div>
<form method="post" action="<?php echo $this->getUrl('*/*/create') ?>">
    <div class="form-group">
        <label for="email">Email address</label>
        <input name="email" type="email" class="form-control" id="email" placeholder="Email">
    </div>
    <div class="form-group">
        <label for="name">Name</label>
        <input name="name" type="text" class="form-control" id="name" placeholder="Name">
    </div>
    <div class="form-group">
        <label for="phone">Phone</label>
        <input name="phone" type="tel" class="form-control" id="phone" placeholder="+38(095)9850477">
    </div>
    <div class="form-group">
        <label for="description">Description</label>
        <textarea name="description" rows="3" class="form-control" id="description" placeholder="Description"></textarea>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=<?= $this->getGoogleApiKey() ?>&callback=initMap">
</script>

